name: moviedbbrowser
description: "A movie browser db"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.2
  path: ^1.8.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true